variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube-check
  - docker-build
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew test

sonarqube-check:
  stage: sonarqube-check
  script:
    - ./gradlew test jacocoTestReport sonar

docker-deploy:
  stage: deploy
  script:
    - docker compose down || true
    - docker network inspect tweetle-network || docker network create tweetle-network
    - docker compose pull
    - docker compose up -d
    - docker ps
  only:
    - main
  dependencies:
    - docker-build